universe                = docker
docker_image            = fragilefort/project-dhvani:v3


executable              = /usr/bin/python
arguments               = -u train_model.py


output                  = logs/job_$(Cluster)_$(Process).out
error                   = logs/job_$(Cluster)_$(Process).err
log                     = logs/job_$(Cluster)_$(Process).log


should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files    = .env, train_model.py


transfer_output_files = results
transfer_output_remaps = "results = results_$(Cluster)"


request_GPUs            = 1
request_CPUs            = 4
request_memory          = 32GB
requirements            = UidDomain == "cs.uni-saarland.de"


+WantGPUHomeMounted     = true
+WantScratchMounted     = true
+MaxRunTime             = 21600
queue 1
